### PR TITLE
Implemented notification system

### PR DESCRIPTION
**Pull request by vivek1842**
Implemented a notification system for the following modal windows: “Buy Now,” “Subscribe,” and “Leave a Review... As there are content in upon modals is not created... I just created a button and added the functionality of notification using sweetalert2... Here's how it looks :  
Screenshot (22)
Screenshot (23)

### CODE REVIEW

**Review by Alexandrbig1 — APPROVED** [review]
Great work! Approved! Great choice of using sweetalert library! Test it, from various devices to be sure that this section is done and we can move forward. As well please, feel free to see our opened issues/tasks for this project: [https://github.com/orgs/OpenCodeChicago/projects/1](https://github.com/OpenCodeChicago/Midwest-Pumpkins/pull/MidwestPumpkin) and if you'll like to work one some let me know before you start, that i can assign you. As well, hope you read our documentation, watched YouTube video, and if you'll like our project, make sure to star it, it'll helps build visibility and showcases your work! Share this project as you contributor to open-source project, add it to your portfolio if you want. Thank you

**Comment by Alexandrbig1** [comment]
@vivek1842 the notification is not working. Let me know if I need to install any packages? I've seen you've added cdn script, but maybe you install any packages locally. Let me know if so. And test it why it's not working. Thank you

**Comment by vivek1842** [comment]
No... I just use cdn script.. and write code of JS in respective js files

**Comment by vivek1842** [comment]
also @Alexandrbig1 does there any more task I can work on.. I checked the opened issues/task but they are already assigned to others

**Comment by Alexandrbig1** [comment]
@vivek1842 is there anyhow the notification should work? If locally is working, figure it out why in our project is not working any notification that you provide me with photos from your local work

**Comment by Alexandrbig1** [comment]
@vivek1842 right now we have footer design and close modal implementation two task that no one is assigned. But first of all finish this one with notification, and then let me know what you want to work on

**Comment by Alexandrbig1** [comment]
@vivek1842 how you achieving it? When click on a button subscribe?
https://opencodechicago.github.io/Midwest-Pumpkins
I don't see any pop-up

**Comment by vivek1842** [comment]
There's a button in subscribe modal as well as review modal... Inside that modal right now there's no content so I just enter like review and there's a submit button in which it's content is "submit" and when you click on submit in front of both review and subscribe modal... Pop up appears i.e. sweetAlert notification

**Comment by Alexandrbig1** [comment]
@vivek1842 this is our website: https://opencodechicago.github.io/Midwest-Pumpkins , when I click on 'subscribe' button, nothing is happening, not any content, no submit button etc.

**Comment by vivek1842** [comment]
I've added functionality to modal's which was mentioned like subscribe modal, review modal, buy modal.... Not to subscribe button which is in page cause that just another part .. actual implementation part is subscribe modal, review modal and buy modal right?

**Comment by Alexandrbig1** [comment]
@vivek1842 finally 😅 now I see Submit text on a button. Great, great notification, everything works well! Need to wait for another contributors to finish their part, and add this logic. You even can add comment for this particular issues, that the people will know what to do. Or wait when they'll finish and add it at that time

**Comment by Alexandrbig1** [comment]
See the open tasks, if you'll find which one is interesting for you, let me know. Thank you!

**Comment by Alexandrbig1** [comment]
also I add you to the documentation as a contributor, but I didn't find your last name, I add just Vivek, if you want to change it or add last name, let me know I'll edit it

**Comment by vivek1842** [comment]
Ok... My last name is 'Ghule' means full name "Vivek Ghule"... You can add that... And I'll check the issue and let you know on which I'll be working... And while making another PR in future ,I'll add that instruction too as a comment so others can understand

**Comment by Alexandrbig1** [comment]
@vivek1842 got it! Thank you!

**Pull request merged**
