### PR TITLE
Add HTML for buy now popup

### PR DESCRIPTION
**Pull request by tanvi4248**

### CODE REVIEW

**Comment by Alexandrbig1** [comment]
@tanvi4248 this task i Believe is by Viktor?

**Comment by Alexandrbig1** [comment]
yeah, it's assigned for him 😅

**Comment by Alexandrbig1** [comment]
you can check another tasks if there not assigned yet, if you finished your hero section

**Comment by tanvi4248** [comment]
[
buy
](url) i thoought it's my task because it's in task description

**Comment by Alexandrbig1** [comment]
@tanvi4248 yes you are right, but just add functionality to open it with javascript, and then Viktor have this issue asigned to him ("Buy Now Pop-Up issue #29")

**Comment by tanvi4248** [comment]
Yes definitely , I am not in a hurry haha...😃

**Comment by Alexandrbig1** [comment]
@tanvi4248 thank you ☺️

**Pull request closed without merging**
