### PR TITLE
add ARIA label for button and javascript for smooth scroll to top-sel…

### PR DESCRIPTION
**Pull request by tanvi4248**
…lers section

### CODE REVIEW

**Comment by Alexandrbig1** [comment]
@tanvi4248 may you add java script function to the specific file? you can find it on js folder in main directory, please

**Comment by tanvi4248** [comment]
There is no specific file for that

**Comment by Alexandrbig1** [comment]
https://github.com/OpenCodeChicago/Midwest-Pumpkins/blob/main/src/js/buy-now-modal.js

**Comment by tanvi4248** [comment]
I added javascript for top sellers button on click scroll

**Comment by tanvi4248** [comment]
not buy now one

**Comment by Alexandrbig1** [comment]
https://github.com/orgs/OpenCodeChicago/projects/1?pane=issue&itemId=81528005

**Comment by Alexandrbig1** [comment]
this button and functionality already finished, you can check it if it's same as yours

**Comment by tanvi4248** [comment]
I was trying to do this functionality -> This button should function as an anchor link, smoothly scrolling the page to the "Top Sellers" section when clicked.
I think i got it i should use HTML instead of javascript

**Comment by Alexandrbig1** [comment]
check his file, I believe he did it well. It's need to observer the window, and when it's over the 200px the button will appear, and then when you clicked it will smoothly bring you to the top. I believe he did it well, you can check his description of his task and the implementation

**Comment by tanvi4248** [comment]
yes he applied for scroll up button but i have to apply on top seller button so maybe that scenario is different.

**Comment by tanvi4248** [comment]
Do I need to create different js file for top seller button js?

**Comment by Alexandrbig1** [comment]
Oh, got it, for top sellers button, sorry 😅

**Comment by Alexandrbig1** [comment]
I believe just add an id to the top sellers section, and that's it. I've already set scroll behavior to smooth on our reset.css file

**Pull request closed without merging**
