### PR TITLE
Add Responsivness

### PR DESCRIPTION
**Pull request by Lakshita-Kumawat**
Add responsiveness to hamburger menu, features, top sale and reviews section

### CODE REVIEW

**Review by Alexandrbig1 — APPROVED** [review]
Great work! Approved! 🚀

**Comment by Alexandrbig1** [comment]
lakshita1
lakshita2

@Lakshita-Kumawat thats how this section looks like, I didn't event checked mobile or tabled devices, it's on desktop. Please make sure you tested before you creating any PR's.

**Comment by Lakshita-Kumawat** [comment]
I have tested it on both

**Comment by Alexandrbig1** [comment]
@Lakshita-Kumawat probably you need to test once again.
here the website you can check it out: https://opencodechicago.github.io/Midwest-Pumpkins

**Comment by Alexandrbig1** [comment]
@Lakshita-Kumawat top sellers is fixed. But feature section need to be changed, if you'll find a time, will be great if you'll fix it. Thank you

**Comment by Lakshita-Kumawat** [comment]
Ok i will try to fix it soon

**Comment by Alexandrbig1** [comment]
@Lakshita-Kumawat thank you! It'll be great!

**Comment by Lakshita-Kumawat** [comment]
@Alexandrbig1 can you tell me which changes you want in the features section? It seems to be responsive for all devices. I think the responsive part is completed.

**Pull request merged**
